import os
import requests
from flask import Flask, request, jsonify, render_template
from dotenv import load_dotenv
from prometheus_client import Counter, generate_latest, CONTENT_TYPE_LATEST

# Initialize Flask app and load environment variables
app = Flask(__name__)
load_dotenv()

# Prometheus counter
REQUEST_COUNT = Counter('chatbot_requests_total', 'Total chatbot API requests')

# Get API key and URL from environment variables
API_KEY = os.getenv("API_KEY")
API_URL = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-preview-05-20:generateContent?key={API_KEY}"

@app.before_request
def before_request():
    REQUEST_COUNT.inc()

@app.route('/')
def index():
    """Renders the main HTML page."""
    return render_template('index.html')

@app.route('/api/generate', methods=['POST'])
def generate_text():
    """Handles the user's prompt and sends it to the Gemini API."""
    if not API_KEY:
        return jsonify({"error": "API key not set"}), 500

    try:
        data = request.get_json()
        prompt = data.get('prompt')

        if not prompt:
            return jsonify({"error": "No prompt provided"}), 400

        payload = {
            "contents": [
                {
                    "role": "user",
                    "parts": [{"text": prompt}]
                }
            ]
        }

        response = requests.post(API_URL, json=payload)
        response.raise_for_status()
        result = response.json()
        
        if result.get('candidates') and result['candidates']:
            text_response = result['candidates'][0]['content']['parts'][0]['text']
            return jsonify({"response": text_response})
        else:
            return jsonify({"error": "No text generated by the model."}), 500

    except requests.exceptions.RequestException as e:
        app.logger.error(f"API request failed: {e}")
        return jsonify({"error": "Failed to connect to the API."}), 500
    except Exception as e:
        app.logger.error(f"An unexpected error occurred: {e}")
        return jsonify({"error": "An unexpected error occurred."}), 500

@app.route('/health')
def health():
    """Health check endpoint."""
    return jsonify({"status": "ok"}), 200

@app.route('/metrics')
def metrics():
    """Prometheus metrics endpoint."""
    return generate_latest(), 200, {'Content-Type': CONTENT_TYPE_LATEST}

if __name__ == '__main__':
    app.run(host='0.0.0.0')
