import os
import requests
from flask import Flask, request, jsonify, render_template

# Initialize Flask app
app = Flask(__name__)

# ---
# CRITICAL: Do NOT hardcode your API key.
# It should always be loaded from an environment variable for security.
# This ensures your key is never committed to Git.
#
# To run this locally, set the environment variable:
#   export API_KEY="your_api_key_here"
# ---
# API_KEY = os.getenv("API_KEY")

API_KEY="AIzaSyABaZT80ukPbyZgcww2sPyTw1cWtnvwhVU"

# Set the API URL to use a stable model
API_URL = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent?key={API_KEY}"

@app.route('/')
def index():
    """Renders the main HTML page."""
    return render_template('index.html')

@app.route('/api/generate', methods=['POST'])
def generate_text():
    """Handles user prompts and sends them to the Gemini API."""
    if not API_KEY:
        app.logger.error("API key is not set.")
        return jsonify({"error": "API key not set"}), 500

    try:
        data = request.get_json()
        prompt = data.get('prompt')

        if not prompt:
            return jsonify({"error": "No prompt provided"}), 400

        # Correct payload format for the Gemini API, including the 'role'
        payload = {
            "contents": [
                {
                    "role": "user",
                    "parts": [
                        {"text": prompt}
                    ]
                }
            ]
        }

        # Make the synchronous API call using the 'requests' library.
        # Note: For production use, consider an async framework to prevent blocking.
        response = requests.post(API_URL, json=payload)
        response.raise_for_status()  # Raises an exception for bad HTTP status codes
        result = response.json()

        if result.get('candidates') and result['candidates']:
            text_response = result['candidates'][0]['content']['parts'][0]['text']
            return jsonify({"response": text_response})
        else:
            app.logger.warning("No text generated by the model.")
            return jsonify({"error": "No text generated by the model."}), 500

    except requests.exceptions.RequestException as e:
        app.logger.error(f"API request failed: {e}")
        return jsonify({"error": "Failed to connect to the API."}), 500
    except Exception as e:
        app.logger.error(f"An unexpected error occurred: {e}")
        return jsonify({"error": "An unexpected error occurred."}), 500

if __name__ == '__main__':
    # This block is for local development only.
    # For production, use a WSGI server like Gunicorn.
    app.run(host='0.0.0.0', port=5000, debug=True)
