apiVersion: v1
kind: Secret
metadata:
  name: chatbot-secret
type: Opaque
data:
  API_KEY: QUl6YVN5RGhsOWFWYjRsRGdwbGNkLTMtRV85ZkppSl9oeHlWS2tz
  API_URL: aHR0cHM6Ly9nZW5lcmF0aXZlbGFuZ3VhZ2UuZ29vZ2xlYXBpcy5jb20vdjFiZXRhL21vZGVscy9nZW1pbmktMS41LWZsYXNoLWxhdGVzdDpnZW5lcmF0ZUNvbnRlbnQ=
