apiVersion: v1
kind: Secret
metadata:
  name: gemini-secret
type: Opaque
stringData:
  API_KEY: "AIzaSyABaZT80ukPbyZgcww2sPyTw1cWtnvwhVU"
  API_URL: "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent"
